---
title: "RoToR viz"
author: "Olivia Brode-Roger"
date: "11/5/2019"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(hrbrthemes)
```

# Data

```{r data, }
sim <- read_csv("data/out.csv")
```

# lkj
```{r buffer, }
cur_ack <- function(rx) {
    buffer <- c()
    cur_ack <- 0
    acks <- c()
    for (r in rx) {
        if (r == cur_ack+1) {
            cur_ack <- cur_ack + 1
            while (TRUE) {
                if ((cur_ack + 1) %in% buffer) {
                    cur_ack <- cur_ack + 1
                } else {
                    break
                }
            }
            buffer <- buffer[cur_ack < buffer]
        } else {
            buffer <- c(buffer, r)
        }
        acks <- c(acks, cur_ack)
    }
    return(acks)
}
cur_ack(xs)

buf_size <- function(rx) {
    buffer <- c()
    cur_ack <- 0
    b_size <- c()
    for (r in rx) {
        if (r == cur_ack+1) {
            cur_ack <- cur_ack + 1
            while (TRUE) {
                if ((cur_ack + 1) %in% buffer) {
                    cur_ack <- cur_ack + 1
                } else {
                    break
                }
            }
            buffer <- buffer[cur_ack < buffer]
        } else {
            buffer <- c(buffer, r)
        }
        b_size <- c(b_size, length(buffer))
    }
    return(b_size)
}
buf_size(xs)
```
# Plot

```{r plot, }
# Remove initial add and intermediate queues
dst_view <- sim %>%
    filter(src != "demand", # remove init
           !grepl(pattern = "-", x = dst_queue)) %>% 
    arrange(time) %>% 
    group_by(dst, dst_queue) %>% 
        mutate(ack = cur_ack(packet),
               buffer_size = buf_size(packet)) %>% 
        ungroup()
    

dst_view %>% 
    filter(time < 3) %>% 
    ggplot(aes(x = time,
               y = packet,
               color = dst_queue)) +
    geom_step(aes(y = ack)) +
    geom_point(size = .2,
               color = "black") +
    facet_grid(dst_queue~dst) +
    labs(x = NULL,
         y = "packet number",
         title = "Packet arrival time and current ack per RoToRnet flow",
         subtitle = "Uniformly random all-to-all flow, 2 slots/cycle, bandwidth 10 packets/slot",
         caption = "https://github.com/nibrivia/rotorsim") +
    guides(color = F) +
    theme_ipsum_rc()

dst_view %>% 
    ggplot(aes(x = time,
               y = buffer_size,
               color = paste(dst, dst_queue))) +
    geom_step() +
    facet_grid(dst_queue~dst) +
    labs(x = NULL,
         y = "Buffer size (packets)",
         title = "Necessary buffer size at end host",
         caption = "https://github.com/nibrivia/rotorsim") +
    guides(color = F) +
    theme_ipsum_rc()

dst_view %>% 
    group_by(buffer_size) %>% 
        summarize(count = n()) %>% 
        ungroup() %>% 
    mutate(frac = count/sum(count)) %>% 
    arrange(buffer_size) %>% 
    ggplot(aes(x = buffer_size,
               y = 1-cumsum(frac))) +
    geom_line() +
    geom_point() +
    scale_y_log10(labels = partial(scales::percent, accuracy = .001)) +
    labs(title = "Drop probability by buffer size",
         subtitle = "RoToRnet guarantees 0 drops for buffers larger than XXX",
         y = NULL,
         x = "Buffer size (packets)",
         caption = "https://github.com/nibrivia/rotorsim") +
    theme_ipsum_rc()
```
