---
title: "opera comparison"
author: "Olivia Brode-Roger"
date: "1/29/2020"
output: html_document
editor_options: 
  chunk_output_type: console
---


```{r data, }
  
require(tidyverse)
require(scales)
require(hrbrthemes)
require(data.table)

load_experiments <- function() {
  tibble(filename = list.files(path = "../data",
                               pattern = ".*ms(.+-){4}.+.csv",
                               full.names = TRUE)) %>% 
    mutate(metadata = map(filename, read_csv, n_max = 1)) %>% 
    unnest(metadata) %>% 
    mutate(done  = grepl("done",  filename),
           drain = grepl("drain", filename),
           time  = lubridate::as_datetime(timestamp, tz = Sys.timezone()),
           type = ifelse(n_rotor == 0, "xpand",
                         ifelse(n_rotor == n_cache, "cache", "opera*")))
}

experiments <- load_experiments()
```

```{r throughput}
opera_cmp_plot <- function(dir, flow_fns) {
  experiments <- tibble(filename = flow_fns) %>%
      mutate(exp_id     = seq_along(filename),
             base_fn    = strsplit(flow_fns, "ms.csv") %>% map_chr(1),# %>% strsplit("drain-") %>% map_chr(2) ,
             split = strsplit(base_fn, "-"),
             n_tor      = as.integer(map_chr(split, 1)),
             n_switches = strsplit(map_chr(split, 2), ":"),
             n_xpand    = as.integer(map_chr(n_switches, 2) %>% strsplit(., ",") %>% map(2)),
             n_cache    = as.integer(map_chr(n_switches, 2) %>% strsplit(., ",") %>% map(1)),
             n_switches = as.integer(map_chr(n_switches, 1)),
             workload   = map_chr(split, 3),
             load       = as.double(map_chr(split, 4)),
             duration   = as.integer(map_chr(split, 5))) %>% 
      #filter(n_cache %in% c(0)) %>% 
      #filter(load %in% c(.1, .4, .8)) %>% 
      select(-split, -base_fn)
  
  flows_nest <- experiments %>% 
    mutate(arrivals = map(paste0(dir, filename), read_csv, col_types = "--iid-dd")) %>% 
    mutate(arrivals = map2(arrivals, exp_id, ~ .x %>% mutate(exp_id = .y)))
  
  flows <- bind_rows(flows_nest$arrivals)
  rm(flows_nest)
  gc()
  
  exp <- experiments[1, ]
  exp$duration <- max(flows$end, na.rm = TRUE)
  lower_limit <- tibble(size_b = 10^(seq(2, 9, length.out = 100)),
                        delay   = (size_b*8/10e9+500e-9)*1e6)
  fcts <- flows %>%
    filter(!is.na(fct)) %>% 
    #filter(load == .01) %>% 
    group_by(exp_id, size) %>% 
      summarize(fct99 = quantile(fct, .99),
                fct   = mean(fct),
                n     = n()) %>% 
      ungroup() %>% 
    left_join(experiments, by = "exp_id") %>% 
    mutate(fct = ifelse(load <= .01, fct, fct99),
           load_name = paste0(100*load, "% load, ", ifelse(load == 0.01, "avg", "99%-ile")))
  

  
  opera_colors <- 
    tribble(
      ~load, ~color,   ~shape,
      .01,   "blue",   1,
      .10,   "red",    3,
      .25,   "orange", 4,
      .30,   "purple", 5,
      .40,   "green",  8
    )
  
  fcts %>% 
    #left_join(opera_colors) %>% 
    mutate(load = as_factor(load*100)) %>% 
    
    #sample_n(10000) %>% 
    #filter(load == .01) %>% 
    ggplot(aes(x = size/8,
               y = fct*1e3,
               color = load_name,
               shape = load_name,
               group = exp_id)) +
    geom_line(show.legend = T) +
    #geom_text(aes(label = n), nudge_y=.5, angle = 45) +
    geom_point() +
    geom_line(data = lower_limit, aes(x=size_b, y = delay), linetype = "dashed",
              inherit.aes = F) +
    geom_vline( xintercept = 15e6, color = "red", linetype = "dashed") +
    scale_x_log10(breaks = 10^(-10:10), label = label_math(format = log10)) +
    scale_y_log10(breaks = 10^((-5:5)*2), label = label_math(format = log10)) +
    theme_ipsum_rc() +
    #scale_color_manual(values = opera_colors$color) +
    #scale_shape_manual(values = opera_colors$shape) +
    
    theme(legend.position = c(.85, .3)) +
    labs(title = "Datamining flow completion times",
         subtitle = paste0(exp$n_tor, " tors ",
                           "for ", exp$duration, "ms. ",
                           exp$n_switches, " switches: ",
                           exp$n_cache, " cache, ",
                           exp$n_xpand, " xpand. "
         ),
         color = NULL, shape = NULL,
         x = "Flow size (bytes)",
         y = "Flow completion time (μs)",
         caption = "github.com/nibrivia/rotorsim")
}

tput_plot <- function(tput_experiments) {
  require(data.table)
  tputs <<- tput_experiments %>% 
    mutate(type = ifelse(n_rotor == 0, "xpand", ifelse(n_rotor == 8, "cache", "opera*"))) %>% 
    mutate(arrivals = map(filename,
                           function(fn) {
                             print(fn)
                             fread(fn, skip = "flow_id") %>% 
                               group_by(src) %>%
                                 summarize(gbits_sent  = sum(sent/1e9),
                                           max_t      = max(start, end, na.rm = TRUE),
                                           n = n()) %>%
                                ungroup() %>% 
                               summarize(mean_sent = mean(gbits_sent)/max(max_t/1e3),
                                         max_time  = max(max_t),
                                         n = sum(n))
                               })) %>% 
    unnest(arrivals)
  
  
  # tputs <<- flows %>%
  #   group_by(exp_id, src) %>%
  #     summarize(gbits_sent = sum(size)/1e9,
  #               max_time   = max(start+fct)) %>%
  #   group_by(exp_id) %>%
  #     summarize(max_time  = max(max_time),
  #               mean_sent = mean(gbits_sent)*1e9/(max_time*1e3)) %>%
  #   left_join(experiments, by = "exp_id")
    
  exp <- tput_experiments[1, ]
  exp$duration <- min(tputs$max_time, na.rm = TRUE)
  tputs %>%
    ggplot(aes(x = load,
               y = mean_sent,
               color = type,
               #color = done,
               group = type)) +
    geom_point() +
    geom_line() +
    
    scale_x_percent(   limits = c(0, 1)) +
    scale_y_continuous(limits = c(0, NA)) +
    
    theme_ipsum_rc() +
    theme(legend.position = c(.05, .15)) +
    labs(title = "Throughput of skewed workload by load",
         subtitle = paste0(exp$n_tor, " tors ",
                           "for ", round(exp$duration), "ms. ",
                           exp$n_switches, " switches: ",
                           exp$n_cache, " cache, ",
                           exp$n_xpand, " xpand. "
         ),
         color = NULL,
         x = NULL,
         y = "Mean ToR tput (Gb/s)",
         caption = "github.com/nibrivia/rotorsim")
}

dir <- "../simulator/"
flow_fns <- list.files(path = dir, pattern = "108-13.*-datamining-0.*-10000ms.csv")
#opera_cmp_plot(dir, flow_fns)


tput_experiments <- load_experiments() %>% 
  ungroup() %>% 
  filter(skewed, n_tor < 130) %>% 
  group_by(load, n_rotor, n_cache, n_xpand) %>%
    top_n(1, timestamp) %>% 
    slice(1) %>% # break ties
    ungroup()
tput_plot(tput_experiments)
```

```{r drain, }
drain256_experiments <- load_experiments() %>% 
  filter(done, n_tor ==256, drain)

drain256_flows <- drain256_experiments %>% 
  select(uuid, filename) %>% 
  mutate(arrivals = map(filename,
                         function(fn) {
                           print(fn)
                           fread(fn, skip = "flow_id")
                             })) %>% 
  select(-filename) %>% 
  unnest(arrivals)

drain256_data <- drain256_flows %>% 
  group_by(uuid, src) %>% 
    summarize(drain_time = max(end),
              size_gb    = sum(size/1e9)) %>% 
  group_by(uuid) %>% 
    summarize(gbits_sent = sum(size_gb),
              mean = weighted.mean(drain_time, wt = size_gb),
              `90%-ile` = quantile(drain_time, .9),
              `99%-ile` = quantile(drain_time, .99),
              max       = max(drain_time)
              ) %>%
    ungroup() %>% 
  reshape2::melt(measure.vars = c("mean", "90%-ile", "99%-ile", "max"),
                 variable.name = "statistic",
                 value.name    = "fct") %>%
  as_tibble() %>% 
  left_join(drain256_experiments, by = "uuid") %>%
  mutate(real_load = gbits_sent/(n_tor*n_switches*10*time_limit/1000))

drain256_data %>%
  ggplot(aes(x = real_load,
             y = fct,
             color = type,
             linetype=type)) +
  geom_point() +
  geom_line() +
  facet_wrap(~statistic) +
  theme_ipsum_rc() +
  geom_abline(slope = 10000/10)

drain256_data %>% 
  select(-hostname, -filename, -time, -done) %>% 
  write_csv("drain-256.csv")
```


```{r fct-ml, }
ml_exp <- load_experiments() %>% 
  filter(is_ml, done, time_limit >= 10000) %>% 
  filter(n_tor == 128) %>% 
  filter(grepl("bf96a4", commit)) %>% 
  group_by(n_tor, load, type, n_switches, n_rotor) %>% 
    top_n(1, time) %>% 
    ungroup()

ml_flows <- ml_exp %>% 
  select(uuid, filename) %>% 
  mutate(arrivals = map(filename,
                         function(fn) {
                           print(fn)
                           fread(fn, skip = "flow_id")
                             })) %>% 
  select(-filename) %>% 
  unnest(arrivals)

ml_data <- ml_flows %>%
  filter(!is.na(fct)) %>%
  mutate(size = as.numeric(size))

ml_data %>% 
  group_by(uuid, size) %>%
    summarize(fct_mean = as.numeric(mean(fct))) %>%
  ungroup() %>%
  left_join(ml_exp, by = "uuid") %>% 
  ggplot(aes(x = size,
             y = fct_mean,
             color = type,
             group = paste(load, type))) +
  geom_point() +
  geom_line() +
  #scale_x_log10() +
  #scale_y_log10() +
  facet_wrap(~load)

n_iter <- ml_data %>%
  filter(size %in% ml_sizes) %>%
  group_by(uuid, size) %>%
  summarize(n=n()) %>%
  left_join(ml_exp %>%
              select(uuid, type, load)) %>%
  arrange(size, load, type)

n_iter %>%
  write_csv("ml-itercount-128.csv")

n_iter %>%
  ggplot(aes(x = as_factor(size),
             y = n,
             fill = type)) +
  geom_col(position = "dodge") +
  facet_grid(load~size, scales = "free")

ml_cdf <- ml_data %>% 
    filter(size %in% ml_sizes) %>% 
  group_by(uuid, size) %>%
    mutate(cdf = percent_rank(fct)) %>% 
  ungroup() %>%
  left_join(ml_exp, by = "uuid") %>% 
  select(-hostname, -filename, -time, -done)

ml_cdf %>% 
  write_csv("ml-cdf-128.csv")

ml_cdf %>% 
  ggplot(aes(x = fct,
             y = cdf,
             color = type,
             group = paste(load, type))) +
  #geom_point() +
  geom_line() +
  #scale_x_log10() +
  #scale_y_log10() +
  facet_grid(size~load, scales = "free")
```

```{r fct-cdf, options}
exps <- 
  experiments %>% 
  filter(n_tor == 128, workload == "datamining", !is_ml, time_limit > 100) %>% 
  group_by(type, load) %>% 
    top_n(1, desc(time))

cdfs <_ function(exps) {
  exps_fows <- exps %>% 
    select(uuid, filename) %>% 
    mutate(arrivals = map(filename,
                          function(fn) {
                            print(fn)
                            fread(fn, skip = "flow_id") %>% 
                              filter(!is.na(fct)) %>%
                              mutate(p = round(percent_rank(fct), 3)) %>% 
                              group_by(p) %>% 
                                summarize(fct = max(fct)) %>% 
                                ungroup()
                          })) %>% 
    select(-filename) %>% 
    unnest(arrivals)
}

```









```{r repeat-run}
mt_old <- file.mtime(paste0(dir, flow_fns))
while(TRUE) {
  mt_new <- file.mtime(paste0(dir, flow_fns))
  if (mt_new != mt_old) {
    try({p <<- opera_cmp_plot(dir, flow_fns)})
    print(p)
    mt_old <- mt_new
  }
  Sys.sleep(5)
}
```
