---
title: "Opera"
author: "Olivia Brode-Roger"
date: "12/21/2019"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
library(tidyverse)
library(hrbrthemes)
library(scales)
```

```{r data, }
opera <- read_csv("opera.csv")
```

```{r plots, }
opera_tors <- opera %>% 
    group_by(time, flow, flow_src, flow_dst, packet) %>% 
        summarize(src = max(src), # t > r, so max gets the tor...
                  dst = max(dst), # this is... hacky...
                  tor = min(src))

opera_tors %>%
    filter(flow %in% c("Flow 21False", "Flow 24True")) %>% 
    #filter(flow %in% c("Flow 32", "Flow 5", "Flow 1", "Flow 24", "Flow 29", "Flow 35", "Flow 31")) %>% 
    ggplot(aes(y = time,
               x = src,
               yend = time+.1,
               xend = dst,
               color = !grepl("True", flow))) +
    geom_segment() +
    scale_y_reverse() +
    theme_ipsum_rc() +
    labs(color = "Low latency") +
    facet_wrap(~flow)
```

```{r large, }
if (FALSE) {
    opera_large <- read_csv("opera-websearch.csv", col_types = "iiiiii")
} else {
    opera_large <- readRDS("opera-large.tbl")
}
```

```{r}
opera_large <- read_csv("opera.csv")
flows <- read_csv("../simulator/flows.csv")

opera_flows <- opera_large %>%
    mutate(time = time/1000) %>% 
    group_by(flow) %>%
        summarize(size = n_distinct(packet)*1500/1e6,
                  n_packets = n(),
                  start = min(time),
                  stop  = max(time)) %>%
        ungroup() %>% 
    mutate(fct = stop-start) %>% 
    left_join(flows, by = c("flow" = "id")) %>% 
    mutate(completed = size >= size_bytes)

opera_flows <- read_csv("opera-65-8-1000-flows.csv")
opera_flows %>%
    #filter(completed) %>% 
    ggplot(aes(x = size*1500/1e6,
               y = fct,
               color = size < 15)) +
    geom_jitter() +
    scale_y_log10(label=comma) +
    scale_x_log10(label=comma) +
    theme_ipsum_rc() +
    labs(title = "FCT for log-uniform distribution™",
         x = "Flow size (MB)",
         y = "Flow completion time (ms)",
         caption = "github.com/nibrivia/rotorsim")
```
